# Habilitar profiling
zmodload zsh/zprof
# ███████╗███████╗██╗  ██╗
# ╚══███╔╝██╔════╝██║  ██║
#   ███╔╝ ███████╗███████║
#  ███╔╝  ╚════██║██╔══██║
# ███████╗███████║██║  ██║
# ╚══════╝╚══════╝╚═╝  ╚═╝
# ────────────────────────────────────────────────────────────
# POWERLEVEL10K INSTANT PROMPT
# Este bloque debe estar cerca del inicio de ~/.zshrc para
# que el prompt se cargue lo antes posible al abrir la terminal.
# NOTA: cualquier código que requiera interacción de usuario
# (passwords, confirmaciones [y/n], etc.) debe ir **antes** de este bloque.
#
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
# ────────────────────────────────────────────────────────────
# ZINIT BOOTSTRAP
# Configuración inicial de Zinit: instala el gestor si no existe
# y lo deja listo para cargar plugins.
#
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
# ────────────────────────────────────────────────────────────
# CONFIGURACIÓN PERSONAL
# Definir ruta base para archivos de configuración adicionales
local ZSH_CONF=~/.config/zsh

# Cargar alias y funciones personalizados
source $ZSH_CONF/kasumi-zsh_alias.conf
source $ZSH_CONF/kasumi-zsh_functions.conf
# ────────────────────────────────────────────────────────────
# AUTO COMPLETADO
# Este código verifica si necesita reconstruir el caché de completado (.zcompdump):
# 1. Si .zcompdump no existe o es más antiguo que .zshrc:
#    - Se carga compinit con seguridad (-Uz)
#    - Se inicializa el sistema ignorando archivos inseguros (-i)
# 2. Si .zcompdump existe y es más reciente que .zshrc:
#    - Se usa el caché existente (-C) para una carga más rápida
#    - Omite las verificaciones de seguridad para mejor rendimiento
#
# Esto asegura que el sistema de completado siempre esté sincronizado con
# tus configuraciones actuales en .zshrc
#
if [[ ! -f ~/.zcompdump || ~/.zcompdump -ot ~/.zshrc ]]; then
    autoload -Uz compinit && compinit -i
else
    # carga rápida sin chequear seguridad de archivos
    compinit -C
fi

# Registro de Zinit en el sistema de completado
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# ┌───────────────────────────────────────────────────────────┐
#   Configuración de TERM para habilitar
#   pre visualización de imágenes en Ranger según la terminal
# └───────────────────────────────────────────────────────────┘
# Se verifica si la sesión actual corresponde a Kitty.
# La variable KITTY_WINDOW_ID es proporcionada automáticamente por Kitty
# y contiene un identificador único de la ventana.
# Se usa para que aplicaciones como ranger puedan determinar
# que el protocolo de imágenes de Kitty puede ser empleado.
#
if [[ "$KITTY_WINDOW_ID" != "" ]]; then
    # Si se está en Kitty, se ajusta TERM a xterm-kitty.
    # Esto es obligatorio para que ranger reconozca la terminal
    # y se puedan mostrar pre visualizaciones de imágenes.
    export TERM="xterm-kitty"
else
    # Para cualquier otra terminal (alacritty, gnome-terminal, etc.)
    # se utiliza xterm-256color para mantener soporte completo de colores.
    export TERM="xterm-256color"
fi
# ────────────────────────────────────────────────────────────
# ▄▀▀▀▀ █▀▀▀▀ ▀▀█▀▀ ▀▀█▀▀ ▀▀█▀▀ █▄  █ ▄▀▀▀▀ ▄▀▀▀▀
#  ▀▀▀▄ █▀▀     █     █     █   █ ▀▄█ █ ▀▀█  ▀▀▀▄
# ▀▀▀▀  ▀▀▀▀▀   ▀     ▀   ▀▀▀▀▀ ▀   ▀  ▀▀▀  ▀▀▀▀
# VARIABLES DE ENTORNO

# Idioma y codificación (comentado porque generó error en Arch)
# export LC_ALL="en_US.UTF-8"

# RANGER
# Desactiva la carga de ajustes predeterminado para rc.conf
export RANGER_LOAD_DEFAULT_RC=FALSE

# USER AGENT
# Personalizado para scripts o utilidades
export IXOS_USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"

# EDITORES
# Definen el editor por defecto para terminal y GUI
export EDITOR="nvim"
export VISUAL="nvim"

# COLORES PARA BAT
export BAT_STYLE="full"
export BAT_THEME="base16"   # Tema de colores compatible con kitty

# COLORES PARA LESS
# Primero tienes que instalar: 'source-highlight'
# export LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s"
export LESSOPEN="| src-hilite-lesspipe.sh %s"      # Coloco únicamente el nombre, sino sirve, prueba con la ruta
export LESS='-MRFI'                                # Estas opciones funcionan en man (en realidad la aplica globalmente)

# COLORES PARA MAN
# Configuraciones que aplican tanto a man como a grep
# export LS_COLORS="*.zip=36:*.rar=36:*.tar=36:*.gz=36:*.tar.gz=36:*.7z=36:$LS_COLORS"
export GREP_COLORS="mt=1;33"              # Resalta en negrita y amarillo las búsquedas con grep
export MANROFFOPT='-c'                    # Activa color en man
export LS_COLORS="ex=30;42"               # Ejecutables con fondo verde

# LESS_TERMCAP
# Controla estilos dentro de less/man
export LESS_TERMCAP_mb=$'\e[1;34m'        # Bold azul
export LESS_TERMCAP_md=$'\e[1;32m'        # Blink verde
export LESS_TERMCAP_so=$'\e[1;33m'        # Reverse video amarillo
export LESS_TERMCAP_us=$'\e[3;35m'        # Underline magenta
export LESS_TERMCAP_me=$'\e[0m'           # Reset bold/blink
export LESS_TERMCAP_se=$'\e[0m'           # Reset reverse video
export LESS_TERMCAP_ue=$'\e[0m'           # Reset underline

# Define LESS como paginador para MAN,
# con soporte de color, formato legible
# y desplazamiento fluido.
export MANPAGER='less -s -M +Gg -R --use-color'    # Pregúntale a GPT, ya lo tuné

# ------------------------------------------------------
# █▀▀▀▀ ▀▀▀▀█ █▀▀▀▀
# █▀▀   ▄▀▀▀  █▀▀
# ▀     ▀▀▀▀▀ ▀
# OPCIONES GENERALES DE FZF

# Generador de TEMAS para fzf
# https://vitormv.github.io/fzf-themes/

# Parámetros globales de fzf: controlan colores,
# diseño y comportamiento por defecto
export FZF_DEFAULT_OPTS="--layout=reverse"   # El prompt se abre desde arriba
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#818F98,fg+:#C8D0D6,bg:-1,bg+:#333C42
  --color=hl:#A88E6B,hl+:#FBC06E,info:#94B8BC,marker:#FF62E0
  --color=prompt:#AFEEAE,spinner:#EA676D,pointer:#FBC06E,header:#87AFAF
  --color=border:#5E6A72,label:#5E6A72,query:#D8DEE2
  --border="sharp"
  --border-label="( 󱐋 )"
  --preview-window="sharp"
  --prompt="󰘧 "
  --info=right
  --marker="›"
  --pointer="▒"
  --separator="─"
  --scrollbar="▐"
' # Fin de linea

# Alt+C (cambio de directorio)
# export FZF_ALT_C_OPTS="--preview 'eza --tree --color=always {} | head -200'"

# Ctrl+T (búsqueda de archivos)
export FZF_CTRL_T_OPTS="--preview 'bat -n --color=always --line-range :500 {}'"

# ------------------------------------------------------
# █   █ ▀▀█▀▀ ▄▀▀▀▀ ▀▀█▀▀ ▄▀▀▀▄ █▀▀▀▄ █   █
# █▀▀▀█   █    ▀▀▀▄   █   █   █ █▀▀▀▄ ▀▀▀▀█
# ▀   ▀ ▀▀▀▀▀ ▀▀▀▀    ▀    ▀▀▀  ▀   ▀ ▀▀▀▀▀
# COMMAND CONFIGURATION

# https://zsh.sourceforge.io/Doc/Release/Variables-Index.html
# https://zsh.sourceforge.io/Doc/Release/Options.html#History

PROMPT_EOL_MARK="🐙"                # Define el símbolo que se mostrará al final de la línea de comandos en el prompt.
HISTFILE=~/.cache/zsh_history       # Archivo donde se guarda el historial
HISTSIZE=30000                      # Comandos que se mantienen en memoria
SAVEHIST=30000                      # Comandos que se guardan en disco
setopt APPEND_HISTORY               # Permite que múltiples sesiones de terminal agreguen comandos al historial en lugar de sobrescribirlo.
setopt BANG_HIST                    # Permite tratar el carácter '!' de manera especial durante la expansión de comandos.
setopt COMPLETE_ALIASES             # Activa la auto completado para alias.
setopt EXTENDED_HISTORY             # Registra la marca de tiempo de cada comando en el archivo de historial en el formato ":inicio:transcurrido;comando".
setopt HIST_ALLOW_CLOBBER           # Permite que las referencias al historial sobrescriban archivos, incluso cuando CLOBBER está desactivado.
setopt HIST_BEEP                    # Emite un pitido cuando se accede a un historial inexistente.
setopt HIST_EXPIRE_DUPS_FIRST       # Elimina comandos duplicados cuando se alcanza el límite de $HISTSIZE.
setopt HIST_FIND_NO_DUPS            # Evita encontrar comandos duplicados durante la búsqueda en el historial.
setopt HIST_IGNORE_ALL_DUPS         # Elimina una entrada anterior en el historial si la nueva es un duplicado.
setopt HIST_IGNORE_DUPS             # Ignora comandos duplicados en la lista del historial.
setopt HIST_IGNORE_SPACE            # Ignora comandos que comienzan con un espacio.
setopt HIST_NO_STORE                # No almacena el comando `fc -l` en el historial.
setopt HIST_REDUCE_BLANKS           # Elimina espacios adicionales de cada línea de comando antes de agregarla al historial.
setopt HIST_SAVE_NO_DUPS            # Ignora duplicados al guardar el historial en el archivo.
setopt HIST_VERIFY                  # Muestra el comando antes de ejecutarlo si se selecciona del historial.
setopt INC_APPEND_HISTORY           # Escribe en el archivo de historial de inmediato, no solo cuando la shell termina.
setopt NO_HIST_NO_FUNCTIONS         # No elimina definiciones de funciones del historial.
setopt RM_STAR_WAIT                 # Espera 10 segundos antes de ejecutar `rm` con un asterisco (*).
setopt SHARE_HISTORY                # Comparte el historial entre todas las sesiones de terminal.

# ┌────────────────────────────────────────────────┐
#   FILTRA EL HISTORIAL DE ZSH ANTES DE GUARDARLO.
#   Solo almacena comandos que existen en el sistema
#   y que no coincidan  con los patrones definidos
#   en HISTORY_IGNORE
# └────────────────────────────────────────────────┘

# Lista de comandos a ignorar
HISTORY_IGNORE="* --help|clear|exa|exit|ls|lsd|man *|pwd|q|ranger|yt-mp3"

# Hook: decidir qué comandos se guardan en el historial
zshaddhistory() {
    local line cmd
    # El comando completo sin salto de línea
    line=${1%%$'\n'}
    cmd=${line%% *}
    # 1. Ignorar si el comando no existe
    whence "$cmd" >| /dev/null || return 1
    # 2. Ignorar si coincide con algún patrón en HISTORY_IGNORE
    [[ $cmd == ${~HISTORY_IGNORE} ]] && return 1
    # 3. Guardar los demás
    return 0
}

# ────────────────────────────────────────────────────────────
# ▀▀▀▀█ ▀▀█▀▀ █▄  █ ▀▀█▀▀ ▀▀█▀▀
# ▄▀▀▀    █   █ ▀▄█   █     █
# ▀▀▀▀▀ ▀▀▀▀▀ ▀   ▀ ▀▀▀▀▀   ▀
# FAST ZSHELL PLUGIN MANAGER

# Tema Powerlevel10k
zinit ice depth=1
zinit light romkatv/powerlevel10k

# FZF Tab Completion (carga bajo demanda)
# zinit ice wait lucid atpull'%atclone'
# zinit light Aloxaf/fzf-tab

# Zsh Autosuggestions (inmediata)
zinit ice wait lucid atload'!_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# Zsh Syntax Highlighting (inmediata)
zinit ice wait lucid
zinit light zsh-users/zsh-syntax-highlighting

# Zsh Completions (carga diferida y segura)
zinit ice wait lucid blockf atpull'zinit creinstall -q .'
zinit light zsh-users/zsh-completions

# ────────────────────────────────────────────────────────────
# setopt clobber                             # Permite que las redirecciones de salida sobrescriban archivos existentes sin confirmación.
# zstyle ':completion:*' special-dirs true   # Muestra directorios especiales ('.' y '..') durante el auto completado de rutas.
# zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*' menu select        # Habilita navegación por menú en el autocompletado (con teclas ↑ ↓)
zstyle ':completion:*' rehash true           # Actualiza la lista de comandos, cada que se instalen nuevos
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' verbose yes
zstyle ':fzf-tab:*' use-fzf-default-opts yes # # https://github.com/Aloxaf/fzf-tab#configure

# ────────────────────────────────────────────────────────────
# ╓
# ║ Zoxide: recuerda los directorios más frecuentados
# ║ Es como cd, pero utilizando el comando z
# ║ Requiere: pacman -S zoxide
# ╙
eval "$(zoxide init zsh)"
# eval "$(zoxide init --cmd cd zsh)"
# ╓
# ║ Integración oficial de fzf
# ║ Proporciona búsquedas interactivas y Ctrl+R mejorado
# ║ Requiere: pacman -S fzf
# ╙
source <(fzf --zsh)

# ────────────────────────────────────────────────────────────
# 💤 Líneas desactivadas (referencia o pruebas)

# Starship prompt (no en uso actualmente)
# Requiere: pacman -S starship
# eval "$(starship init zsh)"
# https://git.nvds.be/NicolaiVdS/Dotfiles/src/commit/66cf71c398c811521d1959c0dbdd19213e2e73ef/.zshrc
# ────────────────────────────────────────────────────────────
# Cargar configuración de Powerlevel10k (si existe)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Coloca esto al final de tu ~/.zshrc
zprof
