#!/usr/bin/env bash
set -euo pipefail
# Descarga letras sincronizadas desde LRCLIB para rmpc.
# Dependencias: curl, jq

# Song metadata
readonly rmpc_artist="${ARTIST:-}"
readonly rmpc_title="${TITLE:-}"
readonly rmpc_album="${ALBUM:-}"

# LRC state
readonly rmpc_has_lrc="${HAS_LRC:-}"
readonly rmpc_lrc_file="${LRC_FILE:-}"

# rmpc runtime
readonly rmpc_pid="${PID:-}"
readonly rmpc_version="${VERSION:-}"

if [ "$rmpc_has_lrc" = "false" ] && [ -n "$rmpc_artist" ] && [ -n "$rmpc_title" ]; then
    mkdir -p "$(dirname "$rmpc_lrc_file")" 2> /dev/null \
        || true # La carpeta padre puede existir

    lyrics=$(curl -X GET -sG \
        -H "Lrclib-Client: rmpc-$rmpc_version" \
        --data-urlencode "artist_name=$rmpc_artist" \
        --data-urlencode "track_name=$rmpc_title" \
        --data-urlencode "album_name=$rmpc_album" \
        "https://lrclib.net/api/get" | jq -r '.syncedLyrics' 2> /dev/null) \
        || true # curl/jq fallan si no hay conexion o la cancion no existe

    if [ -z "$lyrics" ] || [ "$lyrics" = "null" ]; then
        exit
    fi

    {
        echo "[ar:$rmpc_artist]"
        echo "[al:$rmpc_album]"
        echo "[ti:$rmpc_title]"
        echo "$lyrics" | sed -E '/^\[(ar|al|ti):/d'
    } > "$rmpc_lrc_file"

    rmpc remote --pid "$rmpc_pid" indexlrc --path "$rmpc_lrc_file" \
        || true # rmpc pudo haber muerto
fi
