# ┌────────────────────────────────┐
# │░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█│
# │░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀│
# │░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░│
# └────────────────────────────────┘
# ── CONFIGURACIÓN GENERAL ───────────────────────────────────
# https://starship.rs/config/
# https://fossies.org/linux/misc/starship-1.25.0.tar.gz/starship-1.25.0/docs/config/README.md
# https://raw.githubusercontent.com/martinemde/starship-claude/refs/heads/main/plugin/templates/powerline.toml
"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
continuation_prompt = "[▸▹ ](dimmed fg:ka_overlay0)"
scan_timeout = 35
command_timeout = 700

format = """
[▒](fg:ka_crust)\
[ 󰫣  ](fg:ka_teal bg:ka_crust)\
$directory\
$git_branch\
$git_status\
$docker_context\
$fill\
$python\
$status\
$cmd_duration\
$time\
$battery\
$hostname\
$line_break\
$character\
"""

palette = "kasumi_colors"

[palettes.kasumi_colors]
ka_teal = "#89DCEB"
ka_mantle = "#343E43"
ka_overlay0 = "#5D6C74"
ka_crust = "#49575E"
ka_green = "#80C8A1"
ka_red = "#F86E88"
ka_yellow = "#F8E084"
ka_blue = "#A7D6FA"
ka_peach = "#FFCF94"
ka_sapphire = "#BEF7DF"
ka_gray = "#aebbc0"

# ╒════════════════════════════════════════════════════════════╕
# │                      SHELL / ENTRADA                       │
# ╘════════════════════════════════════════════════════════════╛
[character]
success_symbol = "[❯](bold fg:ka_teal)"
error_symbol = "[❯](bold fg:ka_red)"

[fill]
symbol = "┄"
style = "fg:ka_overlay0"

[status]
disabled = false
symbol = "[  ](fg:ka_red) "
success_symbol = "[  ](fg:ka_overlay0) "
format = "$symbol "

# ╒════════════════════════════════════════════════════════════╕
# │                      CONTEXTO USUARIO                      │
# ╘════════════════════════════════════════════════════════════╛
[username]
show_always = true
style_user = "fg:ka_blue"
style_root = "bold fg:ka_red"
format = "[ $user ]($style)"

[hostname]
style = "fg:ka_gray"
# format = '[ $ssh_symbol$hostname]($style)'
format = "[ $hostname]($style)"  # fix
ssh_only = false
ssh_symbol = " "
trim_at = ""

[battery]
full_symbol = "󱐌"
charging_symbol = "󱐌"
discharging_symbol = "󱐌"

# Crítico: solo se muestra cuando batería < threshold
[[battery.display]]
threshold = 20
style = "bold fg:ka_red"

# Advertencia
[[battery.display]]
threshold = 50
style = "fg:ka_yellow"

# Normal
[[battery.display]]
threshold = 100
style = "fg:ka_green"

# ╒════════════════════════════════════════════════════════════╕
# │                         NAVEGACIÓN                         │
# ╘════════════════════════════════════════════════════════════╛
[directory]
style = "fg:ka_mantle bg:ka_teal"
# read_only_style = "fg:color_directory"
# repo_root_style = "bold fg:color_directory"
format = "[](fg:ka_crust bg:ka_teal)[ $path ]($style)[](fg:ka_teal)"
read_only = " "
home_symbol = "~"
truncation_symbol = "‥/"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[directory.substitutions]
"Documents" = "󱔘 "
"Downloads" = "   "
"Music" = " "
"Syncthing" = "   "
"Pictures" = " "

# ╒════════════════════════════════════════════════════════════╕
# │                   CONTENEDORES / RUNTIME                   │
# ╘════════════════════════════════════════════════════════════╛
[docker_context]
symbol = " "
style = "fg:ka_peach"
format = "[ $symbol $context]($style) "

[container]
symbol = "⬢"
style = "fg:ka_red"
format = "[ $symbol $name]($style) "

# ╒════════════════════════════════════════════════════════════╕
# │                         LENGUAJES                          │
# ╘════════════════════════════════════════════════════════════╛
[python]
symbol = " "
style = "fg:ka_blue"
format = "[ $symbol$version]($style) "
version_format = "${raw}"

[lua]
format = "[ $version](bold fg:ka_yellow) "
version_format = "v${major}.${minor}"

[package]
disabled = false
symbol = "󰏗 "
style = "fg:ka_blue"
format = "( [$symbol( $version)]($style) )"

# ╒════════════════════════════════════════════════════════════╕
# │                            GIT                             │
# ╘════════════════════════════════════════════════════════════╛
[git_branch]
symbol = "󰘬 "
style = "fg:ka_mantle bg:ka_green"
format = "[](fg:ka_green)[ $symbol$branch ]($style)[](fg:ka_green) "
# format = "[ $symbol$branch ]($style) "

only_attached = true
truncation_length = 25
truncation_symbol = "..."
disabled = false

[git_commit]
style = "bg:ka_green"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:ka_green"
format = "[$all_status ]($style) "
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
disabled = false

[git_state]
style = "fg:ka_red"
format = "([$state( $progress_current/$progress_total)]($style bold) )"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[git_metrics]
format = "([+$added](added_style) [-$deleted](deleted_style))"
added_style = "fg:ka_green"
deleted_style = "fg:ka_red"
only_nonzero_diffs = true
disabled = true

# ╒════════════════════════════════════════════════════════════╕
# │                     ESTADO DEL SISTEMA                     │
# ╘════════════════════════════════════════════════════════════╛

[time]
disabled = false
style = "fg:ka_blue"
time_format = "%R"
format = "[ $time]($style) "

[cmd_duration]
min_time = 2_000
style = "fg:ka_blue"
format = "[ $duration](bold fg:ka_blue) "

# ╒════════════════════════════════════════════════════════════╕
# │                   MÓDULOS DESHABILITADOS                   │
# ╘════════════════════════════════════════════════════════════╛
[direnv]
disabled = true

# [kubernetes]
# symbol = "☸"
# style = "fg:color_kubernetes"
# format = "[ $symbol $cluster]($style) "
# disabled = true
