add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($container`\n)\
$character"""

right_format = """\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$package\
$docker_context\
$kubernetes\
$container"""

palette = "catppuccin_dark"

[palettes.catppuccin_dark]
color_ok = "#a6e3a1"
color_danger = "#f38ba8"
color_caution = "#f9e2af"
color_os = "#f5c2e7"
color_username = "#b4befe"
color_directory = "#f5c2e7"
color_git = "#a6e3a1"
color_git_added = "#94e2d5"
color_git_deleted = "#eba0ac"
color_env = "#89b4fa"
color_kubernetes = "#89b4fa"
color_docker = "#fab387"
color_shell = "#89dceb"
color_container = "#f9e2af"
color_other = "#cba6f7"
color_time = "#89b4fa"
color_duration = "#f5e0dc"
color_vimcmd_ok = "#a6e3a1"
color_vimcmd_replace = "#cba6f7"
color_vimcmd_visual = "#f9e2af"

[palettes.catppuccin_light]
color_ok = "#40a02b"
color_danger = "#f38ba8"
color_caution = "#df8e1d"
color_os = "#f5c2e7"
color_username = "#f5c2e7"
color_directory = "#df8e1d"
color_git = "#1e66f5"
color_git_added = "#40a02b"
color_git_deleted = "#f38ba8"
color_env = "#89b4fa"
color_kubernetes = "#cba6f7"
color_docker = "#89b4fa"
color_shell = "#6c6f93"
color_container = "#f38ba8"
color_other = "#6c6f93"
color_time = "#575268"
color_duration = "#575268"

color_vimcmd_ok = "#94e2d5"
color_vimcmd_replace = "#cba6f7"
color_vimcmd_visual = "#df8e1d"

[character]
success_symbol = "[]($bold fg:#b4befe)"
error_symbol = "[]($bold fg:#f38ba8)"

[username]
show_always = true
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = "[ $user ]($style)"

[directory]
style = "fg:color_directory"
read_only_style = "fg:color_directory"
repo_root_style = "bold fg:color_directory"
format = "[ $path ]($style)"
read_only = " "
home_symbol = "~"
truncation_symbol = "…/"
truncation_length = 0
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = ""
style = "fg:color_git"
format = "( [$symbol $branch]($style) )"
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "fg:color_git"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = "([$ahead_behind]($style) )([$all_status]($style) )"
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = "([([+$added]($added_style))([-$deleted]($deleted_style))](fg:color_git) )"
added_style = "fg:color_git_added"
deleted_style = "fg:color_git_deleted"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "fg:color_danger"
format = "([$state( $progress_current/$progress_total)]($style bold) )"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[c]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[rust]
symbol = "󱘗"
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[golang]
symbol = "󰟓"
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[php]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[java]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[kotlin]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[haskell]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[python]
symbol = ""
style = "fg:color_env"
format = "( [$symbol( $version)( $virtualenv)]($style) )"
version_format = "${raw}"

[package]
disabled = false
symbol = "󰏗"
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

[docker_context]
symbol = ""
style = "fg:color_docker"
format = "( [$symbol( $context)]($style) )"

[kubernetes]
symbol = "󱃾"
style = "fg:color_kubernetes"
format = "( [($symbol( $cluster))]($style) )"
disabled = false

[container]
style = "fg:color_container"
format = "( [$symbol $name]($style) )"
