# ┌────────────────────────────────┐
# │░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█│
# │░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀│
# │░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░│
# └────────────────────────────────┘
# ── CONFIGURACIÓN GENERAL ───────────────────────────────────
# https://starship.rs/config/
# https://fossies.org/linux/misc/starship-1.25.0.tar.gz/starship-1.25.0/docs/config/README.md
# https://raw.githubusercontent.com/martinemde/starship-claude/refs/heads/main/plugin/templates/powerline.toml
"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
continuation_prompt = "[▸▹ ](dimmed fg:color_line)"
scan_timeout = 35
command_timeout = 700

format = """
[╭─](fg:color_line)\
[](fg:bg_mantle)\
[ 󰫣  ](bg:bg_mantle fg:color_env)\
[](bg:color_directory fg:bg_mantle)\
$directory\
[](fg:color_directory)\
$git_branch\
$git_commit\
$git_status\
$git_state\
$git_metrics\
$docker_context\
$fill\
$python\
$status\
$cmd_duration\
$time\
$battery\
$line_break\
[╰─](fg:color_line)\
$character\
"""

palette = "kasumi_colors"

[palettes.kasumi_colors]
color_ok = "#a6e3a1"
color_danger = "#f38ba8"
color_caution = "#f9e2af"
color_env = "#f5c2e7"
color_username = "#b4befe"
color_directory = "#f5c2e7"
color_git = "#a6e3a1"
color_git_added = "#94e2d5"
color_git_deleted = "#eba0ac"
color_docker = "#fab387"
color_time = "#89b4fa"
color_duration = "#f5e0dc"
color_line = "#5a656c"
# Fondos para formato powerline
bg_directorio = "#89b4fa"  # mismo que color_time
bg_git = "#a6e3a1"  # mismo que color_git/color_ok
bg_docker = "#fab387"  # mismo que color_docker
bg_mantle = "#343E43"

# ╒════════════════════════════════════════════════════════════╕
# │                      SHELL / ENTRADA                       │
# ╘════════════════════════════════════════════════════════════╛
[character]
success_symbol = "[❯](bold fg:color_username)"
error_symbol = "[❯](bold fg:color_danger)"

[fill]
symbol = "┄"
style = "fg:color_line"

[status]
disabled = false
symbol = "[  ](fg:color_danger) "
success_symbol = "[  ](fg:color_line) "
format = "$symbol "

# ╒════════════════════════════════════════════════════════════╕
# │                      CONTEXTO USUARIO                      │
# ╘════════════════════════════════════════════════════════════╛
[username]
show_always = true
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = "[ $user ]($style)"

[battery]
full_symbol = "󰇲 "
charging_symbol = "󰇶 "
discharging_symbol = "󰱪 "

# Crítico
[[battery.display]]
threshold = 15
style = "bold red"

# Bajo
[[battery.display]]
threshold = 40
style = "yellow"

# Normal / siempre visible
[[battery.display]]
threshold = 100
style = "green"

# ╒════════════════════════════════════════════════════════════╕
# │                         NAVEGACIÓN                         │
# ╘════════════════════════════════════════════════════════════╛
[directory]
style = "bg:color_directory fg:bg_mantle"
# read_only_style = "fg:color_directory"
# repo_root_style = "bold fg:color_directory"
format = "[ $path ]($style)"
read_only = " "
home_symbol = "~"
truncation_symbol = "‥/"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[directory.substitutions]
"Documents" = "󱔘 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# ╒════════════════════════════════════════════════════════════╕
# │                   CONTENEDORES / RUNTIME                   │
# ╘════════════════════════════════════════════════════════════╛
[docker_context]
symbol = " "
style = "fg:color_docker"
format = "[ $symbol $context]($style) "

[container]
symbol = "⬢"
style = "fg:color_danger"
format = "[ $symbol $name]($style) "

# ╒════════════════════════════════════════════════════════════╕
# │                         LENGUAJES                          │
# ╘════════════════════════════════════════════════════════════╛
[python]
symbol = " "
style = "fg:color_env"
format = "[ $symbol$version]($style) "
version_format = "${raw}"

[lua]
format = "[ $version](bold fg:color_caution) "
version_format = "v${major}.${minor}"

[package]
disabled = false
symbol = "󰏗 "
style = "fg:color_env"
format = "( [$symbol( $version)]($style) )"

# ╒════════════════════════════════════════════════════════════╕
# │                            GIT                             │
# ╘════════════════════════════════════════════════════════════╛
[git_branch]
symbol = "󰘬 "
style = "fg:color_git"
format = "[ $symbol$branch]($style) "
only_attached = true
truncation_length = 25
truncation_symbol = "..."
disabled = false

[git_commit]
style = "fg:color_git"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = "([$all_status]($style) )"
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
disabled = false

[git_state]
style = "fg:color_danger"
format = "([$state( $progress_current/$progress_total)]($style bold) )"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[git_metrics]
format = "([+$added](added_style) [-$deleted](deleted_style))"
added_style = "fg:color_git_added"
deleted_style = "fg:color_git_deleted"
only_nonzero_diffs = true
disabled = false

# ╒════════════════════════════════════════════════════════════╕
# │                     ESTADO DEL SISTEMA                     │
# ╘════════════════════════════════════════════════════════════╛

[time]
disabled = false
style = "fg:color_time"
time_format = "%R"
format = "[󰥔 $time]($style) "
# format = "[[ 󰥔 $time ]]"

[cmd_duration]
min_time = 2_000
style = "fg:color_duration"
format = "[ $duration](bold fg:color_env) "

# ╒════════════════════════════════════════════════════════════╕
# │                   MÓDULOS DESHABILITADOS                   │
# ╘════════════════════════════════════════════════════════════╛
[direnv]
disabled = true

# [kubernetes]
# symbol = "☸"
# style = "fg:color_kubernetes"
# format = "[ $symbol $cluster]($style) "
# disabled = true
