# ─[ VOLUMEN ]────────────────────────────────────────────────
alias v-='amixer -q set Master 1%-'
alias v+='amixer -q set Master 1%+'
alias v--='amixer -q set Master 15%-'
alias v++='amixer -q set Master 15%+'
alias vmin='amixer -q set Master 0%'
alias v0='amixer -q set Master toggle'
alias v1='amixer -q set Master 10%'
alias v2='amixer -q set Master 20%'
alias v3='amixer -q set Master 30%'
alias v4='amixer -q set Master 40%'
alias v5='amixer -q set Master 50%'
alias v6='amixer -q set Master 60%'
alias v7='amixer -q set Master 70%'
alias v8='amixer -q set Master 80%'
alias v9='amixer -q set Master 90%'
alias vmax='amixer -q set master 100%'
