# ── RGRC COMENTADOS (evaluar para activar) ─────────────────────
# alias df="rgrc df -hT --total -x tmpfs -x devtmpfs -x efivarfs -x squashfs"
# alias dig="rgrc dig"
# alias du="rgrc du -h"
# alias free="rgrc free -m"
# alias ifconfig="rgrc ifconfig"
# alias last="rgrc last -12axw"
# alias lsblk="rgrc lsblk -o NAME,TYPE,MODEL,SIZE,FSTYPE,PARTTYPENAME,MOUNTPOINTS,LABEL -e 7"
# alias netstat="rgrc netstat"
# alias ping="rgrc ping"
# alias ps="rgrc ps"
# alias sensors="rgrc sensors"
# alias stat="rgrc stat"
# alias w="rgrc w --ip-addr"
# alias whois="rgrc whois"
# alias journalctl="rgrc journalctl -f"