# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                           LAYOUT                           │
# ╘════════════════════════════════════════════════════════════╛
  enabled_layouts fat:bias=70;full_size=1;mirrored=false,vertical,horizontal,grid,stack
