# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                          CURSOR                             │
# ╘════════════════════════════════════════════════════════════╛
  cursor                            #FDCD5E
  cursor_shape                      beam
  cursor_beam_thickness             1.5
  focus_follows_mouse               no
  cursor_stop_blinking_after        10

# Ajusta el tiempo que permanece visible el rastro del cursor al moverse.
# trail: muestra el rastro solo si el cursor estuvo inmóvil al menos ~N ms antes de moverse.
# decay: velocidad con que se desvanece el rastro (mínimo y máximo, en segundos).
# threshold: indica cuántas celdas debe moverse el cursor antes de mostrar el rastro..
  cursor_trail                      60
  cursor_trail_decay                0.05 0.2
  cursor_trail_start_threshold      4
