# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                          COLORES                           │
# ╘════════════════════════════════════════════════════════════╛
# ─[ NEGRO ]──────────────────────────────────────────────────
  color0                            #242a2e
  color8                            #5a656c

# ─[ ROJO ]───────────────────────────────────────────────────
  color1                            #ff7770
  color9                            #fbc77f

# ─[ VERDE ]──────────────────────────────────────────────────
  color2                            #7ad99a
  color10                           #aadb9c

# ─[ AMARILLO ]───────────────────────────────────────────────
  color3                            #edb870
  color11                           #FFBB13

# ─[ AZUL ]───────────────────────────────────────────────────
  color4                            #6ab0c3
  color12                           #87b7c7

# ─[ MAGENTA ]────────────────────────────────────────────────
  color5                            #e292e2
  color13                           #EE73D9

# ─[ CYAN ]───────────────────────────────────────────────────
  color6                            #9183c5
  color14                           #9795e5

# ─[ BLANCO ]─────────────────────────────────────────────────
  color7                            #aebbc0
  color15                           #CA8C84

# ╒════════════════════════════════════════════════════════════╕
# │                    COLORES DELTA KASUMI                    │
# ╘════════════════════════════════════════════════════════════╛
  color52                           #5d2e35
  color108                          #8caf90
  color166                          #da8982
  color210                          #fd8c9d
  color240                          #505f67
  color243                          #61ccd1
  color245                          #6f7f89
  color252                          #c5cdd0
