# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                    AJUSTES DE VENTANA                      │
# ╘════════════════════════════════════════════════════════════╛
  initial_window_height             600
  initial_window_width              900
  placement_strategy                center
  remember_window_size              no
  window_resize_step_cells          4
  window_resize_step_lines          4

# ─[ MARGENES DE SEPARACIÓN DE VENTANA ]──────────────────────
  window_margin_width               2 4 4
  window_padding_width              4

# ─[ LINEAS DE VENTANAS ]─────────────────────────────────────
  draw_minimal_borders              yes
  window_border_width               1.5
  active_border_color               #FFCE80
  inactive_border_color             #343c41
  bell_border_color                 #fc697c
