# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                         PESTAÑAS                           │
# ╘════════════════════════════════════════════════════════════╛
# Estos ajustes quedan inactivos por si deseas volver a usarlos
# tab_title_template                "{activity_symbol}{index}›{title}"
# tab_title_max_length 20

  tab_activity_symbol               "✦ "
  tab_title_template                "{activity_symbol}{index}›{title.split('/')[-1]}"

  tab_bar_edge                      top
  tab_bar_style                     powerline
  tab_powerline_style               slanted

  active_tab_foreground             #343c41
  active_tab_background             #6AB0C3
  active_tab_font_style             bold

  inactive_tab_foreground           #687c87
  inactive_tab_background           #343c41
  inactive_tab_font_style           normal

# tab_bar_margin_width              4
# tab_bar_margin_height             1.5 1.5
  tab_bar_margin_color              #2b3135
