# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                       APARIENCIA                           │
# ╘════════════════════════════════════════════════════════════╛

# ─[ TRANSPARENCIA ]──────────────────────────────────────────
  background_opacity                0.94
  inactive_text_alpha               0.75

# ─[ HIPER VÍNCULOS ]─────────────────────────────────────────
  url_style                         double
  url_color                         #F76666
  show_hyperlink_targets            yes

# ╒════════════════════════════════════════════════════════════╕
# │                         LOGO                               │
# ╘════════════════════════════════════════════════════════════╛
# window_logo_path          ~/.config/nvim/lua/kasumi/goodies/puppy-svgrepo-com.svg
# window_logo_alpha         0.1
# window_logo_scale         90
