# vim: filetype=kitty
# ╒════════════════════════════════════════════════════════════╕
# │                           ATAJOS                           │
# ╘════════════════════════════════════════════════════════════╛
  map ctrl+k     launch --type=tab --cwd ~/.kasumi lazygit
  map ctrl+alt+d launch ~/.config/kitty/workflows/kitty-disk-debug.sh
  map ctrl+alt+e launch --stdin-source=@screen_scrollback ~/.config/kitty/utils/scrollback-fzf

# ─[ RESIZE WINDOWS ]─────────────────────────────────────────
  map ctrl+up                       resize_window taller
  map ctrl+down                     resize_window shorter
  map ctrl+left                     resize_window narrower
  map ctrl+right                    resize_window wider
  map ctrl+0                        resize_window reset

# ─[ MOVE ACTIVE WINDOW ]─────────────────────────────────────
  map shift+up                      move_window up
  map shift+down                    move_window down
  map shift+left                    move_window left
  map shift+right                   move_window right

# ─[ FOCUS WINDOW ]───────────────────────────────────────────
  map alt+up                        neighboring_window up
  map alt+down                      neighboring_window down
  map alt+left                      neighboring_window left
  map alt+right                     neighboring_window right

# ─[ LAYOUTS ]────────────────────────────────────────────────
# No puedo usar 'stack' sin antes incluirla en 'enabled_layouts'
# Lo que significa que no puedo declarar atajos con layout que no estén
# previamente definidos.
  map ctrl+1   toggle_layout vertical
  map ctrl+2   toggle_layout horizontal
  map ctrl+3   toggle_layout fat
  map ctrl+4   toggle_layout stack

# ── NOTA: ATAJOS BÁSICOS ────────────────────────────────────
# Son los que trae por defecto pero siempre los olvido
# ctrl + shift + -/+                  - Tamaño de la fuente
# ctrl + shift + backspace            - Restablece el tamaño
# ctrl + shift + area de selección    - Selección en bloque
# ctrl + shift + enter                - Abre una ventana
# ctrl + shift + f                    - Mueve la vista a otra ventana
# ctrl + shift + f5                   - Recargar ajustes
# ctrl + shift + f6                   - Ver ajustes
# ctrl + shift + l                    - Cambia de vista (layout)
# ctrl + shift + t                    - Abre pestaña
# ctrl + Shift + w                    - Cierra la ventana/pane actual (útil si se congela)
# ctrl + Shift + <- / ->              - Alterna entre tabs
# ctrl + Shift + , / .                - Mueve los tabs

# ── COMANDOS ÚTILES ─────────────────────────────────────────
# kitty +list-fonts --psnames         - Para listar fuentes
# kitty @ dump-graphics-state         - Para listar colores
