# vim: filetype=kitty
# ┌──────────────────────────────────────────────┐
# │░█░█░█▀█░█▀▀░█░█░█▄█░▀█▀░░░▀█▀░█░█░█▀▀░█▄█░█▀▀│
# │░█▀▄░█▀█░▀▀█░█░█░█░█░░█░░░░░█░░█▀█░█▀▀░█░█░█▀▀│
# │░▀░▀░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░░░░▀░░▀░▀░▀▀▀░▀░▀░▀▀▀│
# └──────────────────────────────────────────────┘
# https://sw.kovidgoyal.net/kitty/conf/
# 1. Guardar el tema en: ~/.config/kitty/
# 2. Editar el archivo de configuración en: nano ~/.config/kitty/kitty.conf
# 3. Agregar al final: include kasumi.conf
#
# La escala de colores las genero en https://components.ai/color-scale
# Opciones: HSV y Natural / RGB y Lineal
#
# Nomenclatura para colores
# https://www.ditig.com/256-colors-cheat-sheet

# ╒════════════════════════════════════════════════════════════╕
# │                    AJUSTES DE KITTY                        │
# ╘════════════════════════════════════════════════════════════╛
  allow_remote_control              yes
  box_drawing_scale                 1, 0.5, 1, 1
  copy_on_select                    yes
  disable_ligatures                 cursor
  enable_audio_bell                 yes
  open_url_with                     firefox
  scrollback_pager_history_size     10
  strip_trailing_spaces             smart
  sync_to_monitor                   yes

# NOTA: Habilita el atajo de nvim para abrir kitty (vsplit)
  allow_remote_control yes
  listen_on unix:/tmp/kitty

# PEND: probar estos ajustes en otra pc
# wheel_scroll_min_lines            1
# touch_scroll_multiplier           1.5

# WARN: ajustes específicos para Iosevka
# Ajusta la altura de las celdas y la línea base
# para equilibrar acentos visibles e interlineado.
  modify_font cell_height           2px
  modify_font baseline              -1px

  modify_font strikethrough_position -2px
  modify_font underline_position 2px
# modify_font underline_thickness 4px

# ╒════════════════════════════════════════════════════════════╕
# │                    INCLUDE KASUMI.D                         │
# ╘════════════════════════════════════════════════════════════╛
globinclude kasumi.d/*.conf
