#!/bin/sh

# Argumentos recibidos de lf: archivo, ancho, alto, posición x, posición y
file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

# Cache basado en metadatos del archivo
create_cache() {
    mkdir -p "${XDG_CACHE_HOME:-"$HOME/.cache"}/lf"
    CACHE="${XDG_CACHE_HOME:-"$HOME/.cache"}/lf/thumb-$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' \
        -- "$(readlink -f "$1" || realpath "$1")" \
        | xxhsum -q | cut -d' ' -f1)"
}

# DIBUJAR IMÁGENES USANDO EL PROTOCOLO KITTY
draw() {
    kitty +kitten icat --silent --stdin no --transfer-mode memory \
        --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
}

# Obtiene el tipo MIME del archivo
mime=$(file -Lb --mime-type "$file")

# Selecciona el método de previsualización según el tipo de archivo
case "$mime" in
    # ────────────────────────< Imágenes: >──────────────────────
    image/*)
        draw "$file"
        ;;
    # ───────────────────────────< PDFs >───────────────────────────
    application/pdf)
        create_cache "$file"
        [ -f "${CACHE}.jpg" ] || pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
        draw "${CACHE}.jpg"
        ;;
    # ─────────────────────< Archivos comprimidos >────────────────────
    application/zip)
        unzip -l "$file"
        ;;
    application/x-rar)
        unrar l "$file"
        ;;
    application/x-7z-compressed)
        7z l "$file"
        ;;
    application/x-tar | application/gzip)
        tar tf "$file"
        ;;
    # ──────────────────────────< Videos >──────────────────────────
    video/*)
        create_cache "$file"
        [ -f "${CACHE}.jpg" ] || ffmpegthumbnailer -i "$file" -o "${CACHE}.jpg" -s 0 -c jpeg
        draw "${CACHE}.jpg"
        ;;
    # ────────────────────< ARCHIVOS DE TEXTO: >────────────────────
    *)
        bat --color=always --style=plain --paging=never "$file" 2> /dev/null || cat "$file"
        ;;
esac

exit 1
