#!/bin/bash

pkill -f "cava -p" 2> /dev/null

bar_symbol="▁▂▃▄▅▆▇█"
char_map="s/;//g;"

config_file=$HOME/.config/cava/cava-waybar.conf
cat > "$config_file" << 'EOF'
[general]
bars = 12
framerate = 60
sensitivity = 250

[smoothing]
monstercat = 0
gravity = 200
noise_reduction = 0.3

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
EOF

# Crear char_map para reemplazar numeros con simbolos de barra
idx=0
while [ $idx -lt ${#bar_symbol} ]; do
    char_map="${char_map}s/$idx/${bar_symbol:$idx:1}/g;"
    ((idx++))
done

# Agregar espacio después de cada caracter
char_map="${char_map}s/./& /g;"

# Transformar salida de cava usando char_map y mostrar resultado
cava -p "$config_file" | while read -r line; do
    echo "$line" | sed "$char_map"
done
