#!/usr/bin/env bash

dirs=(
    # "$(zoxide query)"
    "$HOME/Documentos"
    "$HOME/Descargas"
    "$HOME/Syncthing/OsiriaFS"
)

selection=$(
    fd . "${dirs[@]}" \
        --type f \
        --hidden \
        --exclude .git \
        | sed "s|^$HOME|~|" \
        | rofi -dmenu -p "Files" -matching glob -case-smart -sort \
            -theme-str '
            listview { lines: 12; columns: 1; dynamic: true; }
            element { padding: 6px; }
            mainbox {
                children: [ inputbar, listview ];
            }
        '
)

[[ -n "$selection" ]] && xdg-open "${selection/#\~/$HOME}"
