#!/usr/bin/env bash

# Pasos de ajuste
STEP_VOL=5
STEP_BRT=2

# Funcion para enviar notificaciones con barra de progreso
notify() {
    local msg="$1"
    local value="$2"
    local channel="$3"

    notify-send \
        -h string:x-canonical-private-synchronous:"$channel" \
        -h int:value:"${value:-0}" \
        -u low \
        -a "media-control" \
        "$msg"
}

case "$1" in
    volume_up)
        # Aumenta volumen y notifica
        pamixer -i "$STEP_VOL"
        LEVEL_VOL=$(pamixer --get-volume)
        notify "Volumen: ${LEVEL_VOL}%" "$LEVEL_VOL" "volume"
        ;;

    volume_down)
        # Disminuye volumen y notifica
        pamixer -d "$STEP_VOL"
        LEVEL_VOL=$(pamixer --get-volume)
        notify "Volumen: ${LEVEL_VOL}%" "$LEVEL_VOL" "volume"
        ;;

    mute)
        # Alterna silencio
        pamixer -t
        if pamixer --get-mute | grep -q true; then
            notify "Audio: mute" 0 "volume"
        else
            LEVEL_VOL=$(pamixer --get-volume)
            notify "Volumen: ${LEVEL_VOL}%" "$LEVEL_VOL" "volume"
        fi
        ;;

    play_pause)
        # Alterna reproduccion y muestra estado
        playerctl play-pause
        MEDIA_STATUS=$(playerctl status 2> /dev/null)

        case "$MEDIA_STATUS" in
            Playing) notify "Reproduciendo" 0 "media" ;;
            Paused) notify "Pausado" 0 "media" ;;
            *) notify "Sin reproduccion activa" 0 "media" ;;
        esac
        ;;

    next)
        playerctl next
        notify "Siguiente pista" 0 "media"
        ;;

    prev)
        playerctl previous
        notify "Pista anterior" 0 "media"
        ;;

    l-up)
        # Aumenta brillo: ajusta, obtiene nivel absoluto, convierte a porcentaje
        brightnessctl set +"$STEP_BRT"%
        LEVEL_BRT=$(brightnessctl get)
        MAX_BRT=$(brightnessctl max)
        PERCENT_BRT=$((LEVEL_BRT * 100 / MAX_BRT))
        notify "Brillo: ${PERCENT_BRT}%" "$PERCENT_BRT" "brightness"
        ;;

    l-down)
        # Disminuye brillo: ajusta, obtiene nivel absoluto, convierte a porcentaje
        brightnessctl set "$STEP_BRT"%-
        LEVEL_BRT=$(brightnessctl get)
        MAX_BRT=$(brightnessctl max)
        PERCENT_BRT=$((LEVEL_BRT * 100 / MAX_BRT))
        notify "Brillo: ${PERCENT_BRT}%" "$PERCENT_BRT" "brightness"
        ;;

    *)
        exit 1
        ;;
esac
