#!/bin/bash
# Gestiona bloqueo automático, apagado de pantalla y suspensión bajo Sway.

LOCK_SCRIPT="$0"

TIMEOUT_LOCK=300     # segundos de inactividad para lock (5 min)
TIMEOUT_DPMS_OFF=600 # segundos totales para dpms off (10 min)
TIMEOUT_SUSPEND=900  # segundos totales para suspend (15 min)

lock_screen() {
    pidof swaylock > /dev/null && exit 0

    BACKGROUND_DIR="$KASUMI_WALLPAPERS_DIR"
    RANDOM_BG=$(find "$BACKGROUND_DIR" -type f | shuf -n 1)

    playerctl pause 2> /dev/null
    swaylock -f -i "$RANDOM_BG"
}

case "$1" in
    lock)
        lock_screen
        ;;
    *)
        swayidle -w \
            timeout $TIMEOUT_LOCK "$LOCK_SCRIPT lock" \
            timeout $TIMEOUT_DPMS_OFF 'swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
            timeout $TIMEOUT_SUSPEND 'systemctl suspend' \
            before-sleep "$LOCK_SCRIPT lock"
        ;;
esac
