# vim: filetype=swayconfig
# ╒═════════════════════════════════════════════════════════════╕
# │                  EJECUTAR AUTOMÁTICAMENTE                   │
# ╘═════════════════════════════════════════════════════════════╛
# Script que va cambiando el fondo del escritorio
# Las dos primeras lineas no son necesarias si empleas solo el
# script de swaybg
  exec_always sh -c 'pkill -x swaybg'
  exec_always sh -c 'pgrep -x awww-daemon >/dev/null || awww-daemon'
  exec --no-startup-id ~/.config/sway/scripts/wall-random-awww

# Agente de autenticación Polkit para Sway :wall-random
# Permite que aplicaciones gráficas soliciten privilegios de administrador
# (por ejemplo, GParted, Balena Etcher) al iniciar Sway.
  exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Inicia el manejador de inactividad (swayidle) para bloqueo,
# apagado de pantalla y suspensión automática
  exec ~/.config/sway/scripts/sway-idle

# Inicia el daemon de notificaciones Mako, activado por D‑Bus.
# Si ya está registrado en la sesión, no se lanza un nuevo proceso
# y se reutiliza el mismo PID (comportamiento esperado).
  exec mako

# Inicia gammastep para ajuste automático de temperatura de pantalla
# Comando de prueba: exec_always pkill -x gammastep; sleep 4; gammastep
  exec gammastep
