# vim: filetype=swayconfig
# ╒═════════════════════════════════════════════════════════════╕
# │                    ATAJOS DE APLICACIONES                    │
# ╘═════════════════════════════════════════════════════════════╛
  bindsym $mod+Return     exec $term
  bindsym $mod+c          exec wl-copy < %f
  bindsym $mod+m          exec $music
  bindsym $mod+n          exec $launcher
  bindsym $mod+p          exec $colorpicker
  bindsym $mod+t          exec $filemanager
  bindsym $mod+x          exec $keepass
  bindsym $mod+Print      exec ~/.config/sway/scripts-legacy/rofi_screenrecord
  bindsym Print           exec ~/.config/sway/scripts/screenshot-region
