# vim: filetype=swayconfig
# ╒═════════════════════════════════════════════════════════════╕
# │                     ATAJOS DE SISTEMA                         │
# ╘═════════════════════════════════════════════════════════════╛
bindsym $mod+Alt+e      exec ~/.config/sway/scripts-legacy/rofi_powermenu
  bindsym $mod+grave      exec ~/.config/sway/scripts-legacy/keybind
  bindsym XF86MonBrightnessDown exec ~/.config/sway/scripts-legacy/backlight --dec
  bindsym XF86MonBrightnessUp   exec ~/.config/sway/scripts-legacy/backlight --inc
