# vim: filetype=swayconfig
# ╒═════════════════════════════════════════════════════════════╕
# │                      ATAJOS RÁPIDOS                          │
# ╘═════════════════════════════════════════════════════════════╛
  bindsym $mod+Return           exec $term
  bindsym $mod+c                exec wl-copy                                 < %f
  bindsym $mod+m                exec $music
  bindsym $mod+n                exec $launcher
  bindsym $mod+p                exec $colorpicker
  bindsym $mod+t                exec $filemanager
  bindsym $mod+x                exec $keepass
# ────────────────────────────────────────────────────────────
  bindsym $mod+Print            exec ~/.config/sway/scripts-legacy/rofi_screenrecord
  bindsym Print                 exec ~/.config/sway/scripts/screenshot-area
  bindsym Shift+Print           exec ~/.config/sway/scripts/screenshot-area swappy
# ────────────────────────────────────────────────────────────
  bindsym $mod+Alt+e            exec ~/.config/sway/scripts-legacy/rofi_powermenu
  bindsym $mod+grave            exec ~/.config/sway/scripts-legacy/keybind
  bindsym XF86MonBrightnessDown exec ~/.config/sway/scripts-legacy/backlight --dec
  bindsym XF86MonBrightnessUp   exec ~/.config/sway/scripts-legacy/backlight --inc
# ────────────────────────────────────────────────────────────
  bindsym $mod+Alt+r      reload
  bindsym $mod+Shift+q    kill
