# vim: filetype=swayconfig
# ╒═════════════════════════════════════════════════════════════╕
# │                       ATAJOS RÁPIDOS                        │
# ╘═════════════════════════════════════════════════════════════╛
  set $scripts ~/.config/sway/scripts
# ────────────────────────────────────────────────────────────
  set $browser          firefox
  set $keepass          keepassxc
  set $colorpicker      hyprpicker --autocopy
  set $filemanager      thunar
  set $launcher         rofi -show drun
  set $music            ~/.config/sway/scripts-legacy/rofi_music
  set $term             kitty
  set $mdeditor         obsidian
# ────────────────────────────────────────────────────────────
  bindsym $mod+Return            exec $term
  bindsym $mod+m                 exec $music
  bindsym $mod+n                 exec $launcher
  bindsym $mod+o                 exec $mdeditor
  bindsym $mod+p                 exec $colorpicker
  bindsym $mod+t                 exec $filemanager
  bindsym $mod+x                 exec $keepass
# ────────────────────────────────────────────────────────────
  bindsym Print                  exec $scripts/screenshot-area
  bindsym Shift+Print            exec $scripts/screenshot-area swappy
  bindsym $mod+z                 exec $scripts/sway-idle lock

# Volumen
  bindsym XF86AudioRaiseVolume   exec $scripts/media-control volume_up
  bindsym XF86AudioLowerVolume   exec $scripts/media-control volume_down
  bindsym XF86AudioMute          exec $scripts/media-control mute

# Multimedia
  bindsym XF86AudioPlay          exec $scripts/media-control play_pause
  bindsym XF86AudioNext          exec $scripts/media-control next
  bindsym XF86AudioPrev          exec $scripts/media-control prev

# Brillo
  bindsym XF86MonBrightnessUp    exec $scripts/media-control l-up
  bindsym XF86MonBrightnessDown  exec $scripts/media-control l-down

# bindsym XF86Search
# ────────────────────────────────────────────────────────────
  bindsym $mod+Alt+e             exec ~/.config/sway/scripts-legacy/rofi_powermenu
  bindsym $mod+grave             exec ~/.config/sway/scripts-legacy/keybind
  bindsym $mod+Print             exec ~/.config/sway/scripts-legacy/rofi_screenrecord
# ────────────────────────────────────────────────────────────
  bindsym $mod+Alt+r      reload
  bindsym $mod+Shift+q    kill
