---
# El manual por si necesitas mas ajustes
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  border: single
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  nerdFontsVersion: '3'
  showFileTree: true
  showIcons: true
  sidePanelWidth: 0.25
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - '#62727c'
    selectedLineBgColor:
      - '#42775a'
    searchingActiveBorderColor:
      - yellow
    # unstagedChangesColor:
    #   - cyan
    # defaultFgColor:
    #   - '#a9b7ba'

git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
