#!/usr/bin/env bash

# Elegir ventana → obtener geometría → capturar con grim + copiar
GEOMETRIA=$(swaymsg -t get_tree | jq -r '.. | select(.pid? and .visible?) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp -f '%x,%y %wx%h') # Aquí usas el default de -f para grim

grim -g "$GEOMETRIA" ~/Imágenes/ventana-"$(date +%s)".png | wl-copy
